Repository Doggy-J-E/Doggy, pull requests merged in 2021-05, with the labels that each got.

#39 Fix issue #31 Display image on the screen
  src/screens/HomeScreen.js
Labels: frontend

#40 Issue #27 - Fix name length cover
  src/config/colors.js
  src/config/screen.js
  src/screens/HomeScreen.js
Labels: frontend

#41 Issue#10 Create DetailsScreen
  package-lock.json
  src/routes/HomeStack.js
  src/routes/WelcomeStack.js
  src/screens/DetailsScreen.js
  src/screens/HomeScreen.js
Labels: design, frontend

#49 Fix issue #46 Fix scaling issue on DetailsScreen
  src/screens/DetailsScreen.js
Labels: design

#51 Fix #29 customize loading screen
  src/component/Indicator.js
  src/component/Loading.js
  src/screens/HomeScreen.js
Labels: design

#52 Issue #50 - Fix scaling issue on HomeScreen
  src/screens/HomeScreen.js
Labels: design

#47 Fix #35 add no results found styling
  src/screens/HomeScreen.js
Labels: design, frontend

#53 Fix #43 Add and apply font
  App.js
  assets/fonts/Nunito-Bold.ttf
  assets/fonts/Nunito-Italic.ttf
  assets/fonts/Nunito-Light.ttf
  assets/fonts/Nunito-Regular.ttf
  assets/fonts/Ubuntu-Bold.ttf
  assets/fonts/Ubuntu-Italic.ttf
  assets/fonts/Ubuntu-Light.ttf
  assets/fonts/Ubuntu-Medium.ttf
  assets/fonts/Ubuntu-Regular.ttf
  src/component/Loading.js
  src/screens/DetailsScreen.js
  src/screens/HomeScreen.js
  src/screens/WelcomeScreen.js
Labels: design

#54 Issue #48 Resolve image issue
  src/screens/DetailsScreen.js
  src/screens/HomeScreen.js
Labels: design

#56 Add icons
  assets/doggy_logo.png
  assets/doggy_logo_with_letter.png
Labels: design

#58 Fix #45 Update top navigation styling
  assets/doggy_logo_grey.png
  src/routes/WelcomeStack.js
Labels: design

#60 Fix issue #59 Change temperament contianer width
  src/screens/DetailsScreen.js
Labels: design

#57 Fix #44 create terms and condition and update logo
  App.js
  assets/fonts/Nunito-Italic.ttf
  assets/fonts/Nunito-Light.ttf
  assets/fonts/Ubuntu-Italic.ttf
  assets/fonts/Ubuntu-Light.ttf
  assets/fonts/Ubuntu-Medium.ttf
  src/component/Loading.js
  src/config/context.js
  src/routes/HomeStack.js
  src/routes/WelcomeStack.js
  src/screens/HomeScreen.js
  src/screens/LoadingScreen.js
  src/screens/TermsConditionScreen.js
  src/screens/WelcomeScreen.js
Labels: design

#63 Fix #62 Update terms and condition content
  src/screens/TermsConditionScreen.js
Labels: documentation

#64 Fix #13 delete unnecessary files and update stack
  App.js
  assets/background-image.jpg
  assets/dogs.jpg
  assets/logo.png
  assets/profile/about-us-1.jpg
  assets/profile/about-us-2.jpg
  src/config/selection.js
  src/config/selectionConfig.js
  src/routes/HomeStack.js
  src/routes/ProfileStack.js
  src/routes/SearchResultStack.js
  src/routes/SearchStack.js
  src/routes/TabsNavigator.js
  src/routes/TermsStack.js
  src/screens/DogTypeSelections/DogColorSelectionScreen.js
  src/screens/DogTypeSelections/DogEnergyLevelSelectionScreen.js
  src/screens/DogTypeSelections/DogSizeSelectionScreen.js
  src/screens/PetTypeSelections/DogTypeSelectionScreen.js
  src/screens/ProfileScreen.js
  src/screens/SearchResultScreen.js
  src/screens/WelcomeScreen.js
Labels: enhancement

#65 Issue #61 Redesign terms and condition
  src/screens/TermsConditionScreen.js
Labels: design

#66 Issue #37 erase vulnerabilities issue
  package-lock.json
  package.json
Labels: warning

#67 Fix Issue #38 and unmount component error
  package-lock.json
  package.json
  src/screens/HomeScreen.js
Labels: frontend, warning

#69 Fix issue #68 Configure app.json
  app.json
  assets/doggy_logo_icon.png
Labels: documentation

#74 Create README.md
  README.md
Labels: documentation

#77 Issue #76 Create snapshot test for LoadingScreen
  .gitignore
  package-lock.json
  package.json
  src/component/Loading.js
  test/LoadingScreen.test.js
Labels: test

#80 Issue #75 Edit README
  README.md
Labels: documentation

#79 Issue #42 Create PetItem component
  src/component/PetItem.js
  src/screens/HomeScreen.js
Labels: design, enhancement, frontend
